site_name: XoL - XPlane on Linux
site_url: https://emvisio.com/
repo_url: https://github.com/mmaechtel/XoL
repo_name: XoL
edit_uri: edit/main/docs/

use_directory_urls: false

theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: de
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.action.edit
    - toc.integrate
    - content.code.copy    # Aktiviert Copy-Buttons für Code-Blöcke
    - content.tabs.link    # Aktiviert Material-Icons

plugins:
  - search:
      lang:
        - en
        - de
      separator: '[\s\-\.]+'
  - pub-blog
  - pub-obsidian:
      backlinks:
        enabled: false
  - i18n:
      docs_structure: folder
      languages:
        - locale: de
          name: Deutsch
          build: true
          default: true
          nav:
            - Startseite: de/index.md
            - Übersicht:
                - Einführung: de/intro.md
                - Erste Schritte: de/begin.md
            - Linux:
                - Übersicht: de/linux.md
                - Optimierungen:
                    - Nvidia Treiber: de/nvidia.md
                    - Liquorix Kernel: de/liquorix.md
                - Erweiterungen:
                    - KVM: de/kvm.md
                    - Docker: de/docker.md
                    - Wine: de/wine.md
                    - pyenv: de/pyenv.md
                    - zsh: de/zsh.md
            - X-Plane:
                - Konfiguration: de/xplane/config.md
            - Szenerien:
                - XOrganizer: de/addon/xorganizer.md
                - Szenerien: de/scenery.md
            - Addons: 
                - Ortho4XP: de/addon/ortho4xp.md
                - AutoOrtho: de/addon/autoortho.md
                - XRoad: de/addon/xroad.md
            - Glossar: de/glossary.md
            - Über: de/about.md
        - locale: en
          name: English
          build: true
          nav:
            - Home: en/index.md
            - Overview:
                - Introduction: en/intro.md
                - Getting Started: en/begin.md
            - Linux:
                - Overview: en/linux.md
                - Optimizations:
                    - Nvidia Drivers: en/nvidia.md
                    - Liquorix Kernel: en/liquorix.md
                - Extensions:
                    - KVM: en/kvm.md
                    - Docker: en/docker.md
                    - Wine: en/wine.md
                    - pyenv: en/pyenv.md
                    - zsh: en/zsh.md
            - X-Plane:
                - Configuration: en/xplane/config.md
            - Sceneries:
                - XOrganizer: en/addon/xorganizer.md
                - Sceneries: en/scenery.md
            - Addons:
                - Ortho4XP: en/addon/ortho4xp.md
                - AutoOrtho: en/addon/autoortho.md
                - XRoad: en/addon/xroad.md
            - Glossary: en/glossary.md
            - About: en/about.md
  - git-revision-date-localized:
      #enable_creation_date: true
      #enabled: !ENV [CI, false]
      #type: date
      #fallback_to_build_date: true
      
extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmaechtel/XoL/issues/new/choose
      name: NewIssue
    - icon: fontawesome/brands/twitter
      link: https://x.com/HeDragonist
      name: X

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          copy_button: true
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true


