site_name: XoL - XPlane on Linux
site_url: https://emvisio.com/
site_description: X-Plane 12 on Linux — Tuning, Drivers, Scenery, and Tools
repo_url: https://github.com/mmaechtel/XoL
repo_name: XoL
edit_uri: edit/main/docs/

use_directory_urls: false

exclude_docs: |
  MARKDOWN_RULES.txt
  CHANGELOG

hooks:
  - hooks/social_cards.py

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.sidebar
    #- navigation.instant          # incompatible with i18n language switcher
    #- navigation.instant.progress
    - toc.follow
    - search.suggest
    - search.highlight
    - content.action.edit
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  language: de

extra_css:
  - stylesheets/fonts.css
  - stylesheets/nav.css

plugins:
  - social
  - search:
      lang:
        - en
        - de
      separator: '[\s\-\.]+'
  - pub-blog
  - pub-obsidian:
      backlinks:
        enabled: false
  - i18n:
      docs_structure: folder
      languages:
        - locale: de
          name: Deutsch
          build: true
          default: true
          nav:
            - Startseite: de/index.md
            - Übersicht:
                - Einführung: de/intro.md
                - Erste Schritte: de/begin.md
                - Performance-Grundlagen: de/performance_overview.md
                - Videos: de/videos.md
            - Linux:
                - Übersicht: de/linux.md
                - Optimierungen:
                    - Nvidia Treiber: de/nvidia.md
                    - Liquorix Kernel: de/liquorix.md
                    - System-Tuning:
                        - Einführung: de/systemtuning_intro.md
                        - Tuning: de/systemtuning.md
                        - System Monitoring: de/systemtools.md
                    - Display-Server:
                        - Übersicht: de/displayserver.md
                        - X11-Session: de/displayserver_x11.md
                        - Wayland-Session: de/displayserver_wayland.md
                    - Dateisystem: de/filesystem.md
                - Erweiterungen:
                    - KVM: de/kvm.md
                    - Docker: de/docker.md
                    - Wine: de/wine.md
                    - pyenv: de/pyenv.md
                    - zsh: de/zsh.md
            - X-Plane:
                - Konfiguration: de/xplane/config.md
                - Performance: de/xplane/performance.md
                - Systemfehler:
                    - Einführung: de/xplane/systemfehler.md
                    - Geräteverluste: de/xplane/geraeteverluste.md
            - Szenerien:
                - Komponenten: de/scenery_components.md
                - Szenerien: de/scenery.md
                - XOrganizer: de/addon/xorganizer.md
            - Addons:
                - Orthofotographie:
                    - Einführung: de/addon/orthophotography_intro.md
                    - Ortho4XP: de/addon/ortho4xp.md
                - Ortho Streaming:
                    - AutoOrtho: de/addon/autoortho.md
                    - XEarthLayer: de/addon/xearthlayer.md
                    - Statisch + Streaming: de/addon/static_plus_streaming.md
                - Scripting:
                    - FlyWithLua: de/addon/flywithlua.md
                    - XPPython3: de/addon/xppython3.md
                - FlyWithLua-Skripte:
                    - 3D Rain Stop: de/addon/3drainspeedstop.md
                    - Dynamic Rain Rate: de/addon/rain_rate.md
                    - SimBrief Simple OFP: de/addon/simbrief_simple_ofp.md
                    - SimLoad Manager: de/addon/simloadmanager.md
                    - SimReaperXP: de/addon/simreaperxp.md
                    - SimScreen Overlay: de/addon/simscreenoverlay.md
                    - SGES: de/addon/sges.md
                - ToLiss-Ökosystem:
                    - Skripte & Plugins: de/addon/toliss_ecosystem.md
                    - Mods: de/addon/toliss_mods.md
                - Sounds:
                    - KOSP Project: de/addon/kosp_project.md
                    - Mango Studios: de/addon/mango_studios.md
                - Cockpit & Kamera:
                    - AviTab: de/addon/avitab.md
                    - XCamera: de/addon/xcamera.md
                    - XTextureExtractor: de/addon/xtextureextractor.md
                    - LinuxTrack: de/addon/linuxtrack.md
                    - TerrainRadar: de/addon/terrainradar.md
                    - KabinXP: de/addon/kabinxp.md
                - Verkehr & Bodenbetrieb:
                    - LiveTraffic: de/addon/livetraffic.md
                    - Better Pushback: de/addon/betterpushback.md
                    - AutoDGS: de/addon/autodgs.md
                    - openSAM: de/addon/opensam.md
                    - AutoGate: de/addon/autogate.md
                    - Follow the Greens: de/addon/followthegreens.md
                - Werkzeuge:
                    - DataRefTool: de/addon/datareftool.md
                    - Little XpConnect: de/addon/littlexpconnect.md
                    - SkunkCrafts Updater: de/addon/skunkcrafts_updater.md
                    - XGS: de/addon/xgs.md
                    - XLinSpeak: de/addon/xlinspeak.md
                    - WINCTRL: de/addon/winctrl.md
                - Szenerie:
                    - XRoad: de/addon/xroad.md
                    - AEP: de/addon/aep.md
                    - xa-snow: de/addon/xa-snow.md
                    - NOAA Weather: de/addon/noaa_weather.md
                    - LST: de/addon/lst.md
                - Via KVM:
                    - My FS Flights: de/addon/myfs_flights.md
                    - MobiFlight: de/addon/mobiflight.md
                    - SayIntentions.AI: de/addon/sayintentions.md
            - Flugbetrieb:
                - Übersicht: de/flight_operations/overview.md
                - Wetter: de/flight_operations/weather.md
                - ATC:
                    - Clearance: de/flight_operations/clearance.md
                    - Pushback & Taxi: de/flight_operations/pushback_taxi.md
                    - Start: de/flight_operations/takeoff.md
                    - Abflug & Steigflug: de/flight_operations/departure.md
                    - Streckenflug: de/flight_operations/enroute.md
                    - Anflug: de/flight_operations/approach.md
                    - Landung & Abstellen: de/flight_operations/landing.md
                - VATSim:
                    - Übersicht: de/flight_operations/vatsim.md
            - Glossar: de/glossary.md
            - Über: de/about.md
        - locale: en
          name: English
          build: true
          nav:
            - Home: en/index.md
            - Overview:
                - Introduction: en/intro.md
                - Getting Started: en/begin.md
                - Performance Fundamentals: en/performance_overview.md
                - Videos: en/videos.md
            - Linux:
                - Overview: en/linux.md
                - Optimizations:
                    - Nvidia Drivers: en/nvidia.md
                    - Liquorix Kernel: en/liquorix.md
                    - System Tuning:
                        - Introduction: en/systemtuning_intro.md
                        - Tuning: en/systemtuning.md
                        - System Monitoring: en/systemtools.md
                    - Display Server:
                        - Overview: en/displayserver.md
                        - X11 Session: en/displayserver_x11.md
                        - Wayland Session: en/displayserver_wayland.md
                    - Filesystem: en/filesystem.md
                - Extensions:
                    - KVM: en/kvm.md
                    - Docker: en/docker.md
                    - Wine: en/wine.md
                    - pyenv: en/pyenv.md
                    - zsh: en/zsh.md
            - X-Plane:
                - Configuration: en/xplane/config.md
                - Performance: en/xplane/performance.md
                - System Errors:
                    - Introduction: en/xplane/systemfehler.md
                    - Device Losses: en/xplane/geraeteverluste.md
            - Scenerien:
                - Komponenten: en/scenery_components.md
                - Scenerien: en/scenery.md
                - XOrganizer: en/addon/xorganizer.md
            - Addons:
                - Orthophotography:
                    - Introduction: en/addon/orthophotography_intro.md
                    - Ortho4XP: en/addon/ortho4xp.md
                - Ortho Streaming:
                    - AutoOrtho: en/addon/autoortho.md
                    - XEarthLayer: en/addon/xearthlayer.md
                    - Static + Streaming: en/addon/static_plus_streaming.md
                - Scripting:
                    - FlyWithLua: en/addon/flywithlua.md
                    - XPPython3: en/addon/xppython3.md
                - FlyWithLua Scripts:
                    - 3D Rain Stop: en/addon/3drainspeedstop.md
                    - Dynamic Rain Rate: en/addon/rain_rate.md
                    - SimBrief Simple OFP: en/addon/simbrief_simple_ofp.md
                    - SimLoad Manager: en/addon/simloadmanager.md
                    - SimReaperXP: en/addon/simreaperxp.md
                    - SimScreen Overlay: en/addon/simscreenoverlay.md
                    - SGES: en/addon/sges.md
                - ToLiss Ecosystem:
                    - Scripts & Plugins: en/addon/toliss_ecosystem.md
                    - Mods: en/addon/toliss_mods.md
                - Sounds:
                    - KOSP Project: en/addon/kosp_project.md
                    - Mango Studios: en/addon/mango_studios.md
                - Cockpit & Camera:
                    - AviTab: en/addon/avitab.md
                    - XCamera: en/addon/xcamera.md
                    - XTextureExtractor: en/addon/xtextureextractor.md
                    - LinuxTrack: en/addon/linuxtrack.md
                    - TerrainRadar: en/addon/terrainradar.md
                    - KabinXP: en/addon/kabinxp.md
                - Traffic & Ground Ops:
                    - LiveTraffic: en/addon/livetraffic.md
                    - Better Pushback: en/addon/betterpushback.md
                    - AutoDGS: en/addon/autodgs.md
                    - openSAM: en/addon/opensam.md
                    - AutoGate: en/addon/autogate.md
                    - Follow the Greens: en/addon/followthegreens.md
                - Tools:
                    - DataRefTool: en/addon/datareftool.md
                    - Little XpConnect: en/addon/littlexpconnect.md
                    - SkunkCrafts Updater: en/addon/skunkcrafts_updater.md
                    - XGS: en/addon/xgs.md
                    - XLinSpeak: en/addon/xlinspeak.md
                    - WINCTRL: en/addon/winctrl.md
                - Scenery:
                    - XRoad: en/addon/xroad.md
                    - AEP: en/addon/aep.md
                    - xa-snow: en/addon/xa-snow.md
                    - NOAA Weather: en/addon/noaa_weather.md
                    - LST: en/addon/lst.md
                - Via KVM:
                    - My FS Flights: en/addon/myfs_flights.md
                    - MobiFlight: en/addon/mobiflight.md
                    - SayIntentions.AI: en/addon/sayintentions.md
            - Flight Operations:
                - Overview: en/flight_operations/overview.md
                - Weather: en/flight_operations/weather.md
                - ATC:
                    - Clearance: en/flight_operations/clearance.md
                    - Pushback & Taxi: en/flight_operations/pushback_taxi.md
                    - Takeoff: en/flight_operations/takeoff.md
                    - Departure & Climb: en/flight_operations/departure.md
                    - En Route: en/flight_operations/enroute.md
                    - Approach: en/flight_operations/approach.md
                    - Landing & Taxi In: en/flight_operations/landing.md
                - VATSim:
                    - Intro: en/flight_operations/vatsim.md
            - Glossary: en/glossary.md
            - About: en/about.md
  - git-revision-date-localized:
      #enable_creation_date: true
      #enabled: !ENV [CI, false]
      #type: date
      #fallback_to_build_date: true

extra:
  alternate:
    - name: Deutsch
      link: /de/
      lang: de
    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mmaechtel/XoL/issues/new/choose
      name: NewIssue
    - icon: fontawesome/brands/discord
      #link: https://discord.gg/2CZWSBprDd
      link: https://discord.gg/S6VkndbfVX
      name: Discord

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          copy_button: true
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
